data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings="?", stringsAsFactors=FALSE)
data$datetime <- strptime(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")
data <- subset(data, (datetime >= "2007-02-01") & (datetime < "2007-02-03"))
par(mfrow=c(2,2), mar=c(4,4,2,1), oma=c(2,1,1,1))
with(data, plot(datetime, Global_active_power, xlab="", ylab="Global Active Power", type="l"))
with(data, plot(datetime, Voltage, type="l"))
with(data, plot(datetime, Sub_metering_1, type="l", ylab="Energy sub metering", xlab=""))
with(data, lines(datetime, Sub_metering_2, col="red"))
with(data, lines(datetime, Sub_metering_3, col="blue"))
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=1, bty="n")
with(data, plot(datetime, Global_reactive_power, type="l"))
dev.copy(png, "plog4.png", width=480, height=480, units="px")
dev.off()