data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings="?", stringsAsFactors=FALSE)
data$timeStamp <- strptime(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")
data <- subset(data, (timeStamp >= "2007-02-01") & (timeStamp < "2007-02-03"))
hist(data$Global_active_power, xlab="Global Active Power (kilowatts)", main="Global Active Power", col="red")
dev.copy(png, "plot1.png", width=480, height=480, units="px")
dev.off()