Sys.setlocale(category="LC_TIME", locale="en_US.utf8")
data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings="?", stringsAsFactors=FALSE)
data$timeStamp <- strptime(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")
data <- subset(data, (timeStamp >= "2007-02-01") & (timeStamp < "2007-02-03"))
with(data, plot(timeStamp, Sub_metering_1, type="l", ylab="Energy sub metering", xlab=""))
with(data, lines(timeStamp, Sub_metering_2, col="red"))
with(data, lines(timeStamp, Sub_metering_3, col="blue"))
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=1)
dev.copy(png, "plot3.png", width=480, height=480, units="px")
dev.off()